### ISSUE TITLE
ModuleNotFoundError: No module named 'web.backend.user'

### ISSUE THREAD

**Issue by kuuer** [royzheng/nas-tools#1]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 启动报错 ModuleNotFoundError: No module named 'web.backend.user'

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 该如何解决

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![捕获](https://github.com/royzheng/nas-tools/assets/78456431/59a4f4fd-0032-41fe-bb93-f126f311e6e1)

**Comment by sheepy928** [comment]
好像是因为docker环境里带的python是3.11，`web.backend.user`是个python 3.10的二进制文件。修改一下Dockerfile里第一行alpine版本为3.17然后重新build就好。

**Comment by royzheng** [comment]
> 好像是因为docker环境里带的python是3.11，`web.backend.user`是个python 3.10的二进制文件。修改一下Dockerfile里第一行alpine版本为3.17然后重新build就好。

谢谢，我这两天rebuild下

**Comment by royzheng** [comment]
@kuuer  已经rebuild了 可以删除本地的这个image重新拉取
@sheepy928 谢谢你的mr
